import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import axios from 'axios';

export default function About({ data }) {
  const [pokemon, setPokemon] = useState({
    data,
  });

  // useEffect(() => {
  //   console.log('loaded');
  //   axios.get('https://pokeapi.co/api/v2/pokemon/pikachu').then((res) => {
  //     setPokemon({ name: res.data.name });
  //     console.log(res.data.name);
  //   });
  // }, []);
  console.log(pokemon.data.name);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 style={{ color: 'red' }}>About Page</h1>
        <p>Welcome to the new about page.</p>
        <h2>Pokemon</h2>
        <p>Name: {pokemon.data.name}</p>
        <br />
      </main>
    </div>
  );
}

// Static Site Generation
// This function gets called at build time
export async function getStaticProps() {
  // Call an external API endpoint to get posts
  const res = await fetch('https://pokeapi.co/api/v2/pokemon/pikachu');
  const data = await res.json();

  // By returning { props: { data } }, the About component
  // will receive `data` as a prop at build time
  return {
    props: {
      data,
    },
  };
}

// Server Side Rendering
// This gets called on every request
// export async function getServerSideProps() {
//   // Fetch data from external API
//   const res = await fetch(`https://.../data`);
//   const data = await res.json();

//   // Pass data to the page via props
//   return { props: { data } };
// }
